import 'aframe'
import 'three'
import 'aframe-extras'
// import 'aframe-html-shader'
// import 'aframe-animation-timeline-component'
import 'aframe-look-at-component'
import './selectable-component'
import './camera'
import './hud/hud-button-component'